export const specMapping = {
  socket: "Сокет",
  cores: "Ядра",
  threads: "Потоки",
  frequency: "Частота",
  cache: "Кэш",
  memory: "Память",
  interface: "Интерфейс",
  ports: "Порты",
  power: "Потребление",
  capacity: "Объём",
  type: "Тип",
  timings: "Тайминги",
  read_speed: "Скорость чтения",
  write_speed: "Скорость записи",
  chipset: "Чипсет",
  memory_slots: "Слотов памяти",
  max_memory: "Макс. память",
  form_factor: "Форм-фактор",
  certificate: "Сертификат",
  modular: "Модульность",
  fan: "Вентилятор",
  motherboard: "Материнская плата",
  max_gpu_length: "Макс. длина GPU",
  max_cooler_height: "Макс. высота кулера",
  diagonal: "Диагональ",
  resolution: "Разрешение",
  matrix: "Матрица",
  refresh_rate: "Частота обновления",
  response_time: "Время отклика",
  curved: "Изогнутый",
  tdp: "TDP",
  fan_size: "Размер вентилятора",
  sockets: "Сокеты",
  switches: "Переключатели",
  backlight: "Подсветка",
  sensor: "Сенсор",
  dpi: "DPI",
  buttons: "Кнопки",
  weight: "Вес",
  microphone: "Микрофон",
};